<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin-PC-1" failures="1" tests="15" name="Sigma.Sigmaoutbound" time="1098.239" errors="0" timestamp="19 Jun 2020 07:22:41 GMT">
  <testcase classname="Sigma.Sigmaoutbound" name="account" time="73.329"/>
  <testcase classname="Sigma.Sigmaoutbound" name="shipment" time="79.377"/>
  <testcase classname="Sigma.Sigmaoutbound" name="VendorContact" time="64.759"/>
  <testcase classname="Sigma.Sigmaoutbound" name="picking" time="82.647"/>
  <testcase classname="Sigma.Sigmaoutbound" name="product" time="89.623"/>
  <testcase classname="Sigma.Sigmaoutbound" name="CustomerContact" time="67.044"/>
  <testcase classname="Sigma.Sigmaoutbound" name="stockreceive" time="144.848"/>
  <testcase classname="Sigma.Sigmaoutbound" name="sigmaordersave" time="10.162"/>
  <testcase classname="Sigma.Sigmaoutbound" name="Cashcustomer" time="118.867"/>
  <testcase classname="Sigma.Sigmaoutbound" name="Package" time="73.944">
    <failure message="1" type="java.lang.ArrayIndexOutOfBoundsException">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at Sigma.Sigmaoutbound.Package(Sigmaoutbound.java:1352)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Package -->
  <testcase classname="Sigma.Sigmaoutbound" name="sigmaorderline" time="40.840"/>
  <testcase classname="Sigma.Sigmaoutbound" name="sigmaorder" time="68.071"/>
  <testcase classname="Sigma.Sigmaoutbound" name="purchaseorder" time="67.664"/>
  <testcase classname="Sigma.Sigmaoutbound" name="Payment" time="83.431"/>
  <testcase classname="Sigma.Sigmaoutbound" name="Aallocation" time="33.633"/>
</testsuite> <!-- Sigma.Sigmaoutbound -->
